version: '2'
services:
  codecept:
      image: vicheus/codeception
      depends_on:
        - chrome
        - firefox
        - mysql
      volumes:
          - '/home/shura/projects/erp/htdocs:/project/'
          - '/home/shura/projects/erp/htdocs/codeception.yml:/project/codeception.yml'
          - '/home/shura/projects/erp/htdocs/tests:/project/tests'
  chrome:
      image: 'selenium/standalone-chrome-debug:2.53.1'
      ports:
          - '5900'
      dns: 8.8.4.4
      environment:
        - no_proxy=localhost
  firefox:
      image: 'selenium/standalone-firefox-debug:2.53.1'
      ports:
          - '5900'
      dns: 8.8.4.4
      environment:
        - no_proxy=localhost
  mysql:
      image: mysql/mysql-server:5.5
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=erp
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root

