NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: "/doc"

api:
    type: rest
    resource: "routing_api.yml"

app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation
